image: "rust:latest"

build:
  stage: build
  parallel:
    matrix:
      - TAG: [linux, shared-windows, shared-macos-amd64]
  tags:
    - $TAG
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/packetraven*
    
lint:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

format:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

audit:
  stage: test
  script:
    - cargo install cargo-audit
    - cargo audit

test:
  stage: test
  script:
    - cargo test

test-slow:
  stage: test
  script:
    - cargo test -- --ignored
