build:
  stage: build
  image: rust:latest
  script:
    - cargo build --release

test:
  stage: test
  image: rust:latest
  script:
    - cargo test

test-slow:
  stage: test
  image: rust:latest
  script:
    - cargo test -- --ignored
