name: test

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test (${{ matrix.runs-on }})
    strategy:
      matrix:
        runs-on:
          - "ubuntu-latest"
          - "macos-latest"  
          - "windows-latest"
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test
